### ISSUE TITLE
"Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture." toggle() called through global event or wrapper component

### ISSUE THREAD

**Issue by andrelec1** [mirari/vue-fullscreen#13]
1. : Register a empty vue component for handle global event.
```js
const EventBus = new Vue({
  name: 'EventBus',
});
Vue.set(Vue.prototype, '$bus', EventBus);
```

2. : Emit event from you desired component 
```js
this.$bus.$emit('fullScreen-toggle');
```
3. :  Listen the event and cry
```js
mounted() {
      this.$bus.$on('fullScreen-toggle', this.setFullScreen);
    },
    beforeDestroy() {
      this.$bus.$off('fullScreen-toggle');
    },
    methods: {
      setFullScreen() {
        this.$refs['fullscreen'].toggle();
      },
},
```

Another try with wrapped component ...
1. Register global component with method
```js
const Test = new Vue({
methodes: {
    async startTest($vm = null) {
        $vm.$root.$children[0].setFullScreen();
    },
},
});

Vue.set(Vue.prototype, '$test', Test);
```
2 : Add this in #app component... 
```js
methods: {
      setFullScreen() {
        this.$refs['fullscreen'].toggle();
      },
```

3. call from another component and cry again ....
```js
this.$test.startTest(this);
```

**Comment by mirari** [comment]
[requestFullscreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)
> This method must be invoked from a user interaction or a device orientation change, else it will fail.

Because of the browser security function, you can only call these methods by a user gesture.
