### ISSUE TITLE
Override Escape Key

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [mirari/vue-fullscreen#18]
Hello,
Is it possible to make it where the escape key can be suppressed or ignored with this component?
I have a component which I am trying to use this on that launches other modal dialogs. The escape key is intended to be used to close my modals, however, I can not seem to bypass this functionality by overriding and preventing propagation on my own.

Can you add an option to ignore the esape key to your code ?

**Comment by mirari** [comment]
I'm afraid it won't work. Exiting the full screen is a browser-level operation and cannot be blocked by blocking the escape key.

**Comment by SmarterPhoneLabs** [comment]
Yeah, I was able to research that on my own as well.
It's ok, thanks for replying
