### ISSUE TITLE
能否支持IE11？

### ISSUE THREAD

**Issue by zbl400** [mirari/vue-fullscreen#2]
试了一下 live demo，发现在 ie11 下不能使用。
请问有办法修改后在 ie11 下用吗？

**Comment by mirari** [comment]
IE11支持已添加，更新到2.0.1版本后再试试。注意只能直接调用方法来切换全屏，vue的值监听触发异步回调在IE11下会被限制。

**Comment by mirari** [comment]
2.1.1修正了之前ES6代码未编译的问题，引入方式有变动，注意更新并修改
