### ISSUE TITLE
Vuetify modal and dropdown is not showing while fullscreen

### ISSUE THREAD

**Issue by bhavinichauhan-easternts** [mirari/vue-fullscreen#23]
In Normal screen, The modal and dropdown is showing properly. But in full screen mode it is not showing.
Please provide the solution for this issue. 
Thank you in advance

**Comment by mirari** [comment]
Only child elements in the fullscreen element are visible.
Tooltip popover element is usually under the `body`.
You can set the `body` element (which is by default) to fullscreen, and change the style of the target element when `body` is fullscreen.
e.g.
```
 this.$fullscreen.toggle()
```
```
<style>
.fullscreen .target-element {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
</style>
```

**Comment by Bhavini30** [comment]
It works. Thank you.

**Comment by buzzclue** [comment]
@mirari this wraps the body in div and then document.body returns null. Any workaround for this?

**Comment by buzzclue** [comment]
Maybe this is how its done?
```js
this.$fullscreen.toggle(document.body, { wrap: false })

**Comment by mirari** [comment]
> Maybe this is how its done?
> 
> ```js
> this.$fullscreen.toggle(document.body, { wrap: false })
> ```

It's a bug, update to 2.3.2, and the `wrap` options will be forced to false if the target is `document.body`, thank you!

**Comment by BoleLee** [comment]
> Only child elements in the fullscreen element are visible.
> Tooltip popover element is usually under the `body`.
> You can set the `body` element (which is by default) to fullscreen, and change the style of the target element when `body` is fullscreen.
> e.g.
> 
> ```
>  this.$fullscreen.toggle()
> ```
> 
> ```
> <style>
> .fullscreen .target-element {
>   position: absolute;
>   top: 0;
>   right: 0;
>   bottom: 0;
>   left: 0;
> }
> </style>
> ```

what if when use vue-fullscreen && vue-grid-layout && (element: el-select | el-date-picker | el-popover) ? 
el-popover, we can set :append-to-body="false";
el-select, set :popper-append-to-body="false" in 2.x;
what about el-date-select ? I have tried to use the method you said, but the position is  limit to grid-item.  https://codepen.io/gracelee/pen/NWpgBZN

**Comment by mirari** [comment]
> > Only child elements in the fullscreen element are visible.
> > Tooltip popover element is usually under the `body`.
> > You can set the `body` element (which is by default) to fullscreen, and change the style of the target element when `body` is fullscreen.
> > e.g.
> > ```
> >  this.$fullscreen.toggle()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > <style>
> > .fullscreen .target-element {
> >   position: absolute;
> >   top: 0;
> >   right: 0;
> >   bottom: 0;
> >   left: 0;
> > }
> > </style>
> > ```
> 
> what if when use vue-fullscreen && vue-grid-layout && (element: el-select | el-date-picker | el-popover) ?
> el-popover and el-date-picker, we can set :append-to-body="false";
> el-select, set :popper-append-to-body="false" in 2.x;
> For some reason, I have to use element in 1.4, the method I said is not working in el-select. I have tried to use the method you said, but the position is limit to grid-item.
> 
> demo: https://codepen.io/gracelee/pen/NWpgBZN
> 
> my version:
> 
> ```
> "vue-fullscreen": "^2.3.5",
> "vue-grid-layout": "^2.3.12"
> "element-ui": "1.4.13"
> ```
> 
> what else can I try? Expecting for your apply! @mirari
添加到body下的弹出框不会被grid-item遮挡，但在grid-item全屏的时候它也无法被展现。
不添加到body，而是放到grid-item下面，虽然全屏时可以看到，但它也会被更高层级的元素遮挡。实际上不是被它的上级grid-item挡住了，而是排位更靠后的其他同级grid-item。
还是让弹窗都放到body下吧，全屏对象设置为body，再单独设置全屏下某个目标的样式
参考这个
https://codepen.io/mirari/pen/xxqrMPZ

但是这种实现方式非常不优雅，因为目标元素总是受父元素影响。
之后考虑加一个body模式，全屏时将目标元素挪到body下，退出时再放回原位

**Comment by BoleLee** [comment]
@mirari 目前用你说的方案暂时满足了当前需求，慢的时候是有一点延迟，要经过body全屏-目标元素改定位的过程。期待你出body模式，我跟着进行升级

**Comment by mirari** [comment]
> @mirari 目前用你说的方案暂时满足了当前需求，慢的时候是有一点延迟，要经过body全屏-目标元素改定位的过程。期待你出body模式，我跟着进行升级

2.5.2已经支持了teleport配置项，专门用于解决弹窗等全屏目标外的元素在全屏时无法看到的问题，使用方式见文档。
另外，支持Vue3的3.x也已经发布了。
