### ISSUE TITLE
Disabling popout close button

### ISSUE THREAD

**Issue by Rhonage** [mirari/vue-fullscreen#27]
Hey there,

First of all - fantastic package! 

Just wondering if there's a way to disable the X in the dark circle that slides in from the top, when the mouse is near the border of the top of the screen?

Thanks in advance.

**Comment by mirari** [comment]
I think it's a browser native behavior, the web page can not affect it.

https://stackoverflow.com/questions/55272678/disabling-fullscreen-x-button
