### ISSUE TITLE
Fullscreen close when i navigate between pages..

### ISSUE THREAD

**Issue by EpitechGuo** [mirari/vue-fullscreen#28]
as title,  fullscreen closed once i navigate to other pages

**Comment by EpitechGuo** [comment]
it works only in single page ?

**Comment by mirari** [comment]
It's closed by the browser, try to use `iframe`.
**
Note: Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
**
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by EpitechGuo** [comment]
> It's closed by the browser, try to use `iframe`.
> 
> > **Note:** Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

有没有什么例子能给我借鉴一下的吗？怎么用上 `<iframe />`

**Comment by mirari** [comment]
> > It's closed by the browser, try to use `iframe`.
> > > **Note:** Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
> > 
> > 
> > https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
> 
> 有没有什么例子能给我借鉴一下的吗？怎么用上 `<iframe />`

https://codepen.io/mirari/pen/VwjyKPL

codepen的预览自己就在iframe里，所以例子两种方式都不会退出全屏

**Comment by EpitechGuo** [comment]
> > > It's closed by the browser, try to use `iframe`.
> > > > **Note:** Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
> > > 
> > > 
> > > https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
> > 
> > 
> > 有没有什么例子能给我借鉴一下的吗？怎么用上 `<iframe />`
> 
> https://codepen.io/mirari/pen/VwjyKPL
> 
> codepen的预览自己就在iframe里，所以例子两种方式都不会退出全屏

谢谢！那除了iframe还有没有别的方法呢？我的网站(Nuxt Vue)已经全部搭建好了 加上iframe的话要改的东西太多了…有没有别的路子？

**Comment by EpitechGuo** [comment]
> > > It's closed by the browser, try to use `iframe`.
> > > > **Note:** Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
> > > 
> > > 
> > > https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
> > 
> > 
> > 有没有什么例子能给我借鉴一下的吗？怎么用上 `<iframe />`
> 
> https://codepen.io/mirari/pen/VwjyKPL
> 
> codepen的预览自己就在iframe里，所以例子两种方式都不会退出全屏

而且我的印象里iframe都是用来取别的网页，总不能把网页全部包在iframe里面吧 不可行的呀

**Comment by mirari** [comment]
> > It's closed by the browser, try to use `iframe`.
> > > **Note:** Navigating to another page, changing tabs, or switching to another application using any application switcher (or Alt-Tab) will likewise exit full-screen mode.
> > 
> > 
> > https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
> 
> 有没有什么例子能给我借鉴一下的吗？怎么用上 `<iframe />`

https://codepen.io/mirari/pen/VwjyKPL

codepen的预览自己就在iframe里，所以例子两种方式都不会退出全屏

**Comment by mirari** [comment]
就是把网页全部包在iframe里面，外层就是一个简单的壳，只负责显示内部内容。
我想不到别的方法了，这是浏览器策略。
