### ISSUE TITLE
execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by hizhengfu** [mirari/vue-fullscreen#3]
vue 2.5.2发现此问题
execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

**Comment by mirari** [comment]
为确保最大兼容性，推荐尽量使用`this.$refs['fullscreen'].toggle()`这种写法来主动调用全屏方法。

**Comment by hizhengfu** [comment]
@mirari 感谢解答。
