### ISSUE TITLE
iPhone Full Screen doesnot work

### ISSUE THREAD

**Issue by AliCemilcan** [mirari/vue-fullscreen#32]
Hi, I am testing on iPhone 8 software version 14.2 and it does not do anything. It works well on android devices.

**Comment by mirari** [comment]
[https://caniuse.com/fullscreen](https://caniuse.com/fullscreen)
Sadly all iPhones don't support the fullscreen API.

**Comment by mirari** [comment]
[https://caniuse.com/fullscreen](https://caniuse.com/fullscreen)
Sadly all iPhones does not support the full screen API.

**Comment by AliCemilcan** [comment]
`.leaflet-pseudo-fullscreen {
	position: fixed !important;
	width: 100% !important;
	height: 100% !important;
	top: 0px !important;
	left: 0px !important;
	z-index: 99999;
}`
This worked for me
