### ISSUE TITLE
Are there plans to support VUE3

### ISSUE THREAD

**Issue by snoobcn** [mirari/vue-fullscreen#37]
The authors have plans to support vue3 ?

**Comment by mirari** [comment]
I expect to do this before the early May.

**Comment by eikowagenknecht** [comment]
Any news on this? :-)

**Comment by mirari** [comment]
Sorry for the delay. Under refactoring and will be released in 1-2 weeks,  thank you for your attention!

**Comment by mirari** [comment]
https://github.com/mirari/vue-fullscreen/tree/v3
Vue3 version has been released, welcome to use and feedback, thanks for your support.

**Comment by TianVast** [comment]
Hello author, I introduced and registered vuefullscreen in vue3, but it always reminds me that $fullscreen doesn't exist. I feel very confused. Please help me to analyze the problem.

**Comment by mirari** [comment]
> Hello author, I introduced and registered vuefullscreen in vue3, but it always reminds me that $fullscreen doesn't exist. I feel very confused. Please help me to analyze the problem.

What is your `vue-fullscreen` version number? The old version of the ts declaration file is incorrect and needs to be updated to the latest version

**Comment by TianVast** [comment]
> > 作者你好，我在vue3中引入并注册了vuefullscreen，但是总是提醒我$fullscreen不存在。我感到很困惑。请帮我分析问题。
> 
> 你的`vue-fullscreen`版本号是多少？老版本的ts声明文件不正确，需要更新到最新版本
My is 3.0.5. Registering app. Use (vuefull screen) or app. Use (vuefull screen. Default) in main.js will report an error. Either $fullscreen cannot be found or toggle is not a function. I'm a little confused.

**Comment by mirari** [comment]
> > > 作者你好，我在vue3中引入并注册了vuefullscreen，但是总是提醒我$fullscreen不存在。我感到很困惑。请帮我分析问题。
> > 
> > 
> > 你的`vue-fullscreen`版本号是多少？老版本的ts声明文件不正确，需要更新到最新版本
> > My is 3.0.5. Registering app. Use (vuefull screen) or app. Use (vuefull screen. Default) in main.js will report an error. Either $fullscreen cannot be found or toggle is not a function. I'm a little confused.

Update to `3.0.10` and try again. Sorry for the problem with the previous version of the declaration file.

**Comment by TianVast** [comment]
> > Hello author, I introduced and registered vuefullscreen in vue3, but it always reminds me that $fullscreen doesn't exist. I feel very confused. Please help me to analyze the problem.
> 
> What is your `vue-fullscreen` version number? The old version of the ts declaration file is incorrect and needs to be updated to the latest version

Thank you for upgrading to 3.0.10
