### ISSUE TITLE
fullscreen status check

### ISSUE THREAD

**Issue by nunob87** [mirari/vue-fullscreen#4]
How do I know the status of the fullscreen?

**Comment by mirari** [comment]
bind data like `:fullscreen.sync="fullscreen"`
or listen the change event like `@change="fullscreenChange"`

**Comment by nunob87** [comment]
needed to check the status, because it has several fullscreen ones inside each other, and needed to test each separately for the case of another child of the other, to cancel all.

**Comment by mirari** [comment]
I forgot to update the doc.
You can use `this.$fullscreen.getState()` to get the fullscreen status from any vue component.

**Comment by nunob87** [comment]
thank you
