### ISSUE TITLE
antv x6的拖拽wrapper和 elementui 的message弹框依旧会被盖住哦

### ISSUE THREAD

**Issue by AmazingWood** [mirari/vue-fullscreen#41]
antvx6拖拽过程中生成的ghost样式和 elementui中的提示信息框依旧会被盖住，无论teleport被设置为true还是false。。。

**Comment by mirari** [comment]
能提供一下复现的测试用例吗，可以参考demo的格式

**Comment by AmazingWood** [comment]
> 能提供一下复现的测试用例吗，可以参考demo的格式

如果确认不行，我晚些给您，我也查一下是不是自己使用问题~

**Comment by AmazingWood** [comment]
我是傻（），我错了，估计是我自己用的有问题，我写了个demo，没有遮挡问题，裂开了啊啊啊啊啊啊啊啊啊啊。感谢开发者费心了！
