### ISSUE TITLE
建议把until.js里let变量修改为var 。在项目里使用时，npm run dev正常。npm run build打包报错

### ISSUE THREAD

**Issue by cynthiawupore** [mirari/vue-fullscreen#5]
export function extend () {
  const extended = {}
  var deep = false
  var i = 0
  const length = arguments.length

  if (Object.prototype.toString.call(arguments[0]) === '[object Boolean]') {
    deep = arguments[0]
    i++
  }

  function merge (obj) {
    for (var prop in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, prop)) {
        if (deep && Object.prototype.toString.call(obj[prop]) === '[object Object]') {
          extended[prop] = extend(true, extended[prop], obj[prop])
        } else {
          extended[prop] = obj[prop]
        }
      }
    }
  }

  for (var i = 0; i < length; i++) {
    var obj = arguments[i]
    merge(obj)
  }

  return extended
}

**Comment by mirari** [comment]
不要引入npm包的源码，引入的话需要在webpack中指定对node_modules目录下库脚本也进行babel转码。
正常情况下使用import Fullscreen from 'vue-fullscreen'得到的是Babel转译过的发布版，里面没有let和const这种关键字。
```
function extend() {
  var extended = {};
  var deep = false;
  var i = 0;
  var length = arguments.length;

  if (Object.prototype.toString.call(arguments[0]) === '[object Boolean]') {
    deep = arguments[0];
    i++;
  }

  function merge(obj) {
    for (var prop in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, prop)) {
        if (deep && Object.prototype.toString.call(obj[prop]) === '[object Object]') {
          extended[prop] = extend(true, extended[prop], obj[prop]);
        } else {
          extended[prop] = obj[prop];
        }
      }
    }
  }

  for (; i < length; i++) {
    var obj = arguments[i];
    merge(obj);
  }

  return extended;
}
```
