### ISSUE TITLE
vue3注册插件时报错

### ISSUE THREAD

**Issue by ruo-an-an** [mirari/vue-fullscreen#55]
通过app.use(VueFullscreen)注册时报了这个错误

vue-fullscreen.min.js:1 Uncaught TypeError: Cannot set properties of undefined (setting '$fullscreen')
    at Object.install (vue-fullscreen.min.js:1:6671)
    at Object.use (runtime-core.esm-bundler.js:3752:18)
    at main.ts:16:5

**Comment by mirari** [comment]
vue3要用`vue-fullscreen@next`安装

**Comment by ruo-an-an** [comment]
不好意思，node包是装对了，重启一下就不报错了，谢谢哈
