### ISSUE TITLE
Blank Full screen

### ISSUE THREAD

**Issue by nwaughachukwuma** [mirari/vue-fullscreen#6]
Hey @mirari  and @balping the full screen is going blank and only comes up after clicking on the blank screen. This has been experienced for 3rd slide :index=2. What could be the problem? Eagerly expecting your response. Thanks

**Comment by mirari** [comment]
Could you post some sample code?
You can use jsfiddle like this:
[https://jsfiddle.net/mirari/kb0ssh5j/](https://jsfiddle.net/mirari/kb0ssh5j/)

**Comment by nwaughachukwuma** [comment]
Hey @mirari thanks for the swift response. The code is quite long and some dependencies are not available over CDN so I used pastebin here: https://pastebin.com/bX9kSszA. The first 2 and last components can be seen on fullscreen, but the 3rd one cannot. I don't know what could be responsible for this. I have only put the code for one of the components to avoid too lengthy lines of codes. Let me know if you get the gist. Thanks

**Comment by mirari** [comment]
It seems like the 3rd component is no different from others.
Does the devtool console have any output?

Have you try to change the order and make sure if the order is the cause of the problem, or the very component?

**Comment by nwaughachukwuma** [comment]
@mirari I experienced the same thing when I switched it. Even when I use same component in the different positions. More so, I didn't get any message on the devtool console.

**Comment by mirari** [comment]
Make sure the component has the correct width and height, and is not including popups which are appended to body or other element.
All elements outside the fullscreen component are invisible.
Sorry I can't offer any more advice before I see the actual page.
