### ISSUE TITLE
Vue3 ts 注册组件报错

### ISSUE THREAD

**Issue by Happy66688** [mirari/vue-fullscreen#60]
npm install vue-fullscreen@next
"vue-fullscreen": "^3.1.1"
![111](https://github.com/mirari/vue-fullscreen/assets/65072040/9c40b372-5beb-4fba-b00f-9e336261fc91)
![222](https://github.com/mirari/vue-fullscreen/assets/65072040/599c7a68-3dbf-4675-a0c8-6b209fab4105)
![333](https://github.com/mirari/vue-fullscreen/assets/65072040/2584bdf3-d184-494c-acd7-2b5cdad521a9)

**Comment by mirari** [comment]
ts注册的错误是package的声明语法过时了，刚发布了3.1.2，更新一下试试。
TS错误应该不会影响代码执行，实际还是能使用的，如有问题欢迎继续反馈。

**Comment by Happy66688** [comment]
好的，我试一下

**Comment by Happy66688** [comment]
![112233](https://github.com/mirari/vue-fullscreen/assets/65072040/72bc2209-76b8-4827-808b-9f2b4dbff02b)
依然渲染不出来，代码：
      <fullscreen v-model="fullscreen">
        content
      </fullscreen>

**Comment by Happy66688** [comment]
![代码](https://github.com/mirari/vue-fullscreen/assets/65072040/6251b600-daf3-4ed7-923a-611a52ff9405)
刚才粘贴的有问题，这个是代码

**Comment by mirari** [comment]
可能是setup语法下组件名跟变量名同名导致的
将变量fullscreen改成其他名字试试，比如isFullscreen

https://stackblitz.com/edit/vitejs-vite-j6mgx4?file=src%2FApp.vue

**Comment by Happy66688** [comment]
确实是这个问题，谢谢
