### ISSUE TITLE
Browser security rejecton: Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by imShara** [mirari/vue-fullscreen#7]
### How to reproduce:
```
vue init webpack fullscreen-test
cd fullscreen-test
npm install --save vue-fullscreen
npm run dev
```

Edit `./src/components/HelloWorld.vue`
``` vue
<template>
  <div class="hello">
    <fullscreen :fullscreen.sync="fullscreen">
      Content
    </fullscreen>
    <button type="button" @click="toggle" >Fullscreen</button>
  </div>
</template>

<script>
import fullscreen from 'vue-fullscreen'
import Vue from 'vue'
Vue.use(fullscreen)

export default {
  name: 'HelloWorld',
  methods: {
    toggle () {
      this.fullscreen = !this.fullscreen
    }
  },
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
      fullscreen: false
    }
  }
}
</script>
```
### Research:
``` html
// Not working through vue-fullscreen recommended method
<button type="button" @click="toggle" >vue-fullscreen</button>

// Works with direct-called plain mozilla fulscreen-request
<button type="button" onclick="body.mozRequestFullScreen()" >onclick fullscreen</button>

// Works with plain mozilla fulscreen-request called from vuejs method
<button type="button" @click="full" >vue-method fullscreen</button>
```
``` js
methods: {
  toggle () {
    this.fullscreen = !this.fullscreen
  },
  full () {
    document.body.mozRequestFullScreen()
  }
}
```

Tested in Chrome, Fireox

**Comment by mirari** [comment]
The trigger mechanism from the new version of Vue.js has been modified, you have to trigger it like this now:
```
      toggle () {
        this.$refs['fullscreen'].toggle()
        // this.fullscreen = !this.fullscreen
      }
```

**Comment by imShara** [comment]
Ok, thanks. But if just replace `this.fullscreen = !this.fullscreen` methhod function to `this.$refs['fullscreen'].toggle()`, you have got `TypeError: this.$refs.fullscreen is undefined`.

You should also add `ref="fullscreen"` to `<fullscreen>` tag like [here](https://github.com/mirari/vue-fullscreen#use-as-component)

Readme update required.

**Comment by mirari** [comment]
Yes, I will update it later.

**Comment by BartlomiejSkwira** [comment]
@mirari do you know how to handle a case where the click occurs in a different (nested) component?  The case:
Component nesting:
ComponentA - has fullscreen html
..... ComponentB (nested in A) - has enable/disable fullscreen checkbox

1. Click checkbox in B
2. Click handler modifies Vuex store variable `fullscreen`
3. Component A watches `fullscreen` variable
4. On `fullscreen` change launches `this.$refs['fullscreen'].toggle()` -> results in js error `Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.` happens.

It all works fine if the checkbox is in ComponentA. Ideas?

**Comment by mirari** [comment]
@BartlomiejSkwira 
Since the prop watcher can not be a sync action now, the browser will intercept the subsequent operation of the callback.Change the `fullscreen` variable or trigger from it will not work.
You have to excute the `toggle` method directly from a click callback or the chain of it now.
