### ISSUE TITLE
SyntaxError: Unexpected token 'const'

### ISSUE THREAD

**Issue by nwaughachukwuma** [mirari/vue-fullscreen#8]
Hey @mirari I keep getting following error when running the package in a linux based system (even on a docker instance)
`SyntaxError: Unexpected token 'const' at webpack:///~/vue-fullscreen/src/utils.js:2:0 <- index.js:291193`

What could be the problem?

**Comment by mirari** [comment]
Don't import it from `src`, or you need to use babel to convert the new syntax.
